apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: distributed-tracing-operator
  namespace: openshift-distributed-tracing
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace