apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio
spec:
  configuration:
    env:
      - name: REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED
        value: 'true'
    kafkasql:
      bootstrapServers: 'fights-kafka-bootstrap:9092'
    persistence: kafkasql
